### ISSUE TITLE
Remove dark highlight from keypad confirm button

### ISSUE THREAD

**Issue by C-ollins** [raedahgroup/dcrios#416] opened 2019-05-27 12:10 UTC
Keypad's confirm button shows a dark highlight in pressed state. The dark highlight looks off and should be removed.
<img src="https://user-images.githubusercontent.com/19960200/58418674-59118380-8080-11e9-80df-fc935b67fcf2.PNG" width="300">

**Comment by raedah** [comment] 2019-05-29 04:34
This also looks to be caused by there being no indicator of what dcrlibwallet operation is occuring, and should have been fixed as part of https://github.com/raedahgroup/dcrios/issues/354

**Comment by itswisdomagain** [comment] 2019-05-29 23:37
https://github.com/raedahgroup/dcrios/issues/416#issuecomment-496780138 was fixed in #347. That PR introduced display of loading indicators after entering PIN or Password on the pin/password page.

**Closed** 2019-05-29 23:45 UTC
